# Generated by Django 4.1.1 on 2022-09-20 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='aboutme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='cv',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.IntegerField()),
                ('ano', models.IntegerField()),
                ('texto_cv', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='verindex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=60)),
                ('tipo', models.IntegerField()),
                ('imagen', models.ImageField(upload_to='uploads/')),
                ('texto', models.CharField(max_length=600)),
                ('fechapost', models.DateField()),
                ('autor', models.CharField(max_length=10)),
            ],
        ),
    ]
