# Generated by Django 4.1.1 on 2022-09-20 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miblogApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_portfolio', models.IntegerField()),
                ('imagen_portfolio', models.ImageField(upload_to='uploads/portfolio/')),
                ('texto_portfolio', models.CharField(max_length=20)),
            ],
        ),
        migrations.DeleteModel(
            name='aboutme',
        ),
    ]
