# Generated by Django 4.1.1 on 2022-09-21 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('miblogApp', '0002_portfolio_delete_aboutme'),
    ]

    operations = [
        migrations.CreateModel(
            name='blog',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('miblogApp.verindex',),
        ),
    ]
