# Generated by Django 4.1.1 on 2022-10-16 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miblogApp', '0005_remove_portfolio_imagen_portfolio_portfolio_giturl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='giturl',
            field=models.URLField(),
        ),
    ]
