# Generated by Django 4.1.1 on 2022-10-16 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miblogApp', '0008_remove_portfolio_tipo_portfolio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='texto_portfolio',
            field=models.CharField(max_length=200),
        ),
    ]
